[project]
name = 'Decentralized-Cross-Chain-Liquidity-Aggregation'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.arbitrage-optimization]
path = 'contracts/arbitrage-optimization.clar'
clarity_version = 2
epoch = 2.5

[contracts.bridge-coordination]
path = 'contracts/bridge-coordination.clar'
clarity_version = 2
epoch = 2.5

[contracts.liquidity-discovery]
path = 'contracts/liquidity-discovery.clar'
clarity_version = 2
epoch = 2.5

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
